version: "3.2"
services:
  pid:
    image: sbinnani/udacity-pid-docker:latest
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./
        target: /pid

    command: bash -c "mkdir -p /pid/build &&
                      cd /pid/build && 
                      cmake .. && make && ./pid > /pid/out.txt"

volumes:
  .: